# Starbie – bill of materials

<!-- Generated by Half Life from project cmuuux18g0asq01smn2t3hz5q. Edits here are overwritten on the next sync. -->
<!-- Generated: 2026-10-06T19:46:42.380Z -->

> [!NOTE]
> This parts list is mirrored from [Half Life](https://halflife.hackclub.com). Editing it here will not change the platform's copy, and the next sync overwrites this file.

| Week | Tier | Parts funding |
| --- | --- | --- |
| Week 1 | Tier 1 | $30.00 |

| Part | What it's for | Qty | Unit | Total | Vendor |
| --- | --- | --- | --- | --- | --- |
| [Seeed XIAO ESP32C3](https://www.unmannedtechshop.co.uk/products/seeed-xiao-esp32c3?variant=56578247623037&country=GB%C2%A4cy=GBP&utm_medium=product_sync&utm_source=google&utm_content=sag_organic&utm_campaign=sag_organic&srsltid=AU7gw4VCbMzJZ-xUdSQhj6p-ogy97dOR99agcFbLWUc_ytfiRsq4UcQjf3s) | Main Loop | 1 | $6.36 | $6.36 | [unmannedtech](https://www.unmannedtechshop.co.uk/products/seeed-xiao-esp32c3?variant=56578247623037&country=GB%C2%A4cy=GBP&utm_medium=product_sync&utm_source=google&utm_content=sag_organic&utm_campaign=sag_organic&srsltid=AU7gw4VCbMzJZ-xUdSQhj6p-ogy97dOR99agcFbLWUc_ytfiRsq4UcQjf3s) |
| [Keyboard Switches](https://www.aliexpress.com/item/1005012561363452.html?spm=a2g0o.cart.0.0.266038daJ28lto&mp=1&pdp_npi=6%40dis%21GBP%21GBP+13.76%21GBP+6.01%21%21GBP+6.01%21%21%21%400b0fe08917913159496472481e0fe6%2112000058735438858%21ct%21UK%21-1%21%211%210%21) | The Switches | 1 | $7.98 | $7.98 | [aliexpress](https://www.aliexpress.com/item/1005012561363452.html?spm=a2g0o.cart.0.0.266038daJ28lto&mp=1&pdp_npi=6%40dis%21GBP%21GBP+13.76%21GBP+6.01%21%21GBP+6.01%21%21%21%400b0fe08917913159496472481e0fe6%2112000058735438858%21ct%21UK%21-1%21%211%210%21) |
| [Keycaps](https://www.aliexpress.com/item/1005012146547025.html?spm=a2g0o.cart.0.0.230838daoKq0Zi&mp=1&pdp_npi=6%40dis%21GBP%21GBP+1.81%21GBP+1.81%21%21GBP+1.81%21%21%21%400b0fe08917913152635525357e0fe6%2112000057621889494%21ct%21UK%21-1%21%211%210%21) | The Keyboard Switches | 1 | $2.40 | $2.40 | [aliexpress](https://www.aliexpress.com/item/1005012146547025.html?spm=a2g0o.cart.0.0.230838daoKq0Zi&mp=1&pdp_npi=6%40dis%21GBP%21GBP+1.81%21GBP+1.81%21%21GBP+1.81%21%21%21%400b0fe08917913152635525357e0fe6%2112000057621889494%21ct%21UK%21-1%21%211%210%21) |
| [OLED Display Module](https://www.aliexpress.com/item/1005006141235306.html?spm=a2g0o.cart.0.0.230838daoKq0Zi&mp=1&pdp_npi=6%40dis%21GBP%21GBP+2.25%21GBP+2.25%21%21GBP+2.25%21%21%21%400b0fe08917913152635525357e0fe6%2112000035944225406%21ct%21UK%21-1%21%211%210%21) | The screen | 1 | $2.99 | $2.99 | [aliexpress](https://www.aliexpress.com/item/1005006141235306.html?spm=a2g0o.cart.0.0.230838daoKq0Zi&mp=1&pdp_npi=6%40dis%21GBP%21GBP+2.25%21GBP+2.25%21%21GBP+2.25%21%21%21%400b0fe08917913152635525357e0fe6%2112000035944225406%21ct%21UK%21-1%21%211%210%21) |
| [GY-521 MPU-6050 Module](https://www.aliexpress.com/item/1005009728452529.html?spm=a2g0o.cart.0.0.230838daoKq0Zi&mp=1&pdp_npi=6%40dis%21GBP%21GBP+4.19%21GBP+4.19%21%21GBP+4.19%21%21%21%400b0fe08917913152635525357e0fe6%2112000060325208396%21ct%21UK%21-1%21%211%210%21) | Gyro | 1 | $1.13 | $1.13 | [aliexpress](https://www.aliexpress.com/item/1005009728452529.html?spm=a2g0o.cart.0.0.230838daoKq0Zi&mp=1&pdp_npi=6%40dis%21GBP%21GBP+4.19%21GBP+4.19%21%21GBP+4.19%21%21%21%400b0fe08917913152635525357e0fe6%2112000060325208396%21ct%21UK%21-1%21%211%210%21) |
| [Temp and Humidity Sensor](https://www.aliexpress.com/item/1005009073170322.html?spm=a2g0o.cart.0.0.230838daoKq0Zi&mp=1&pdp_npi=6%40dis%21GBP%21GBP+2.12%21GBP+1.01%21%21GBP+1.01%21%21%21%400b0fe08917913152635525357e0fe6%2112000047819045375%21ct%21UK%21-1%21%211%210%21) | Temp and Humidity Sensing | 1 | $1.34 | $1.34 | [aliexpress](https://www.aliexpress.com/item/1005009073170322.html?spm=a2g0o.cart.0.0.230838daoKq0Zi&mp=1&pdp_npi=6%40dis%21GBP%21GBP+2.12%21GBP+1.01%21%21GBP+1.01%21%21%21%400b0fe08917913152635525357e0fe6%2112000047819045375%21ct%21UK%21-1%21%211%210%21) |
| [Resistor](https://www.aliexpress.com/item/1005006632157517.html?spm=a2g0o.cart.0.0.230838daoKq0Zi&mp=1&pdp_npi=6%40dis%21GBP%21GBP+1.20%21GBP+1.15%21%21GBP+1.15%21%21%21%400b0fe08917913152635525357e0fe6%2112000037878668245%21ct%21UK%21-1%21%211%210%21) | Resisting | 1 | $1.53 | $1.53 | [aliexpress](https://www.aliexpress.com/item/1005006632157517.html?spm=a2g0o.cart.0.0.230838daoKq0Zi&mp=1&pdp_npi=6%40dis%21GBP%21GBP+1.20%21GBP+1.15%21%21GBP+1.15%21%21%21%400b0fe08917913152635525357e0fe6%2112000037878668245%21ct%21UK%21-1%21%211%210%21) |
| **Parts subtotal** | — | — | — | **$23.73** | — |
| **Tax & shipping** | — | — | — | **$4.63** | — |
| **Total** | — | — | — | **$28.36** | — |

$1.64 left of the tier's funding.
